### ISSUE TITLE
react-redux-i18n Under redux-saga

### ISSUE THREAD

**Issue by stellarArg** [artisavotins/react-redux-i18n#13]
Hey, Great work im trying to run this code under redux-saga but i got severals erros when im trying to dispatch cause of the plain objects, do u have any suggestion, thx in advance, im kinda new on this

**Comment by OrianeInMoon** [comment]
@stellarArg did you succeeded to make it work with redux-saga?

**Comment by mackbrowne** [comment]
@OrianeInMoon this won't work with sagas.  The actions created by this package do not return pure json objects, therefore it ends up being really messy with sagas.

I switch to [redux-i18n](https://www.npmjs.com/package/redux-i18n) which plays much nicer with sagas.

There's nothing wrong with this library.  And if I was using thunk instead of sagas, it would probably be my translation lib of choice.

**Comment by kinjiro** [comment]
It work for me.

in store.js i have : 

```javascript
sagaMiddleware.run(IndexSagas);
syncTranslationWithStore(store);
```

and then in i18saga.js i have :

```javascript
import { put } from "redux-saga/effects";
import langs from "../lang"

export default function* i18nFlowSaga() {
  const lang = navigator.language || "fr";
  yield put({ type: 'loadTranslation', translations: langs });
  yield put({ type: 'setLocal', locale: lang });
}
```

**Comment by t1gor** [comment]
@kinjiro thanks for sharing. How did you do the `i18next.onLanguageChange`, if it's not a secret?
